environment:
  NuGetApiKey:
    secure: 8YkGfuwtA1voj3pVNxbyatmJbhEn82hV+41hVTf9r3efcfuhEH2OEunUzOltIpdf

build: false

test_script:
  - ps: . .\build.ps1

skip_commits:
  files:
    - .gitattributes
    - .gitignore
    - LICENSE
    - README.md